### ISSUE TITLE
Reset link does not change the console fqdn after change and reapply of chart

### ISSUE THREAD

**Issue by venu-rafay** [paralus/helm-charts#41]
- Go to Console->System-User
- Goto 3-dots for a given user and click on 'Reset Password', and
- Password Reset Link is shown but it does not match the configured fqdn..

<img width="1324" alt="Screenshot 2022-07-08 at 1 08 56 PM" src="https://user-images.githubusercontent.com/14259816/177986550-08b508c6-fc80-4e9b-a477-8859be382249.png">

**Comment by akshay196** [comment]
@venu-rafay This has been fixed in `main`.
