### ISSUE TITLE
Installed Paralus on EKS cluster using helm , not able to access the dashbaord

### ISSUE THREAD

**Issue by divyanjali1** [paralus/helm-charts#79]
### Describe the issue you're facing

I have installed paralus using helm chart in EKS cluster.But the contour envoy is not accessible.

EKS cluster version : 1.22

**Comment by akshay196** [comment]
@divyanjali1 Can you please add more details like error you're getting while accessing Paralus or logs you see in pods?

**Comment by divyanjali1** [comment]
This isssue is now resolved. I have used hosted zone and created ingress for dashboard and relay service which resolved the issue.

**Comment by akshay196** [comment]
Great. Closing this issue.
